#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BraintreeV2Example.Resource", IsApplication=true)]

namespace BraintreeV2Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010020
			public const int ambientEnabled = 2130772000;
			
			// aapt resource value: 0x7f010000
			public const int appTheme = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int buyButtonAppearance = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int buyButtonHeight = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int buyButtonText = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int buyButtonWidth = 2130771973;
			
			// aapt resource value: 0x7f010011
			public const int cameraBearing = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int cameraTargetLat = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int cameraTargetLng = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int cameraTilt = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int cameraZoom = 2130771989;
			
			// aapt resource value: 0x7f010023
			public const int circleCrop = 2130772003;
			
			// aapt resource value: 0x7f010001
			public const int environment = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int fragmentMode = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int fragmentStyle = 2130771970;
			
			// aapt resource value: 0x7f010022
			public const int imageAspectRatio = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int imageAspectRatioAdjust = 2130772001;
			
			// aapt resource value: 0x7f010016
			public const int liteMode = 2130771990;
			
			// aapt resource value: 0x7f010010
			public const int mapType = 2130771984;
			
			// aapt resource value: 0x7f01000a
			public const int maskedWalletDetailsBackground = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int maskedWalletDetailsButtonBackground = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int maskedWalletDetailsButtonTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int maskedWalletDetailsHeaderTextAppearance = 2130771977;
			
			// aapt resource value: 0x7f01000e
			public const int maskedWalletDetailsLogoImageType = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int maskedWalletDetailsLogoTextColor = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int maskedWalletDetailsTextAppearance = 2130771976;
			
			// aapt resource value: 0x7f010024
			public const int tokenizationKey = 2130772004;
			
			// aapt resource value: 0x7f010017
			public const int uiCompass = 2130771991;
			
			// aapt resource value: 0x7f01001f
			public const int uiMapToolbar = 2130771999;
			
			// aapt resource value: 0x7f010018
			public const int uiRotateGestures = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int uiScrollGestures = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int uiTiltGestures = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int uiZoomControls = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int uiZoomGestures = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int useViewLifecycle = 2130771997;
			
			// aapt resource value: 0x7f01000f
			public const int windowTransitionStyle = 2130771983;
			
			// aapt resource value: 0x7f01001e
			public const int zOrderOnTop = 2130771998;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050017
			public const int bt_base_background = 2131034135;
			
			// aapt resource value: 0x7f050021
			public const int bt_black = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int bt_blue = 2131034146;
			
			// aapt resource value: 0x7f050018
			public const int bt_blue_pressed = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int bt_border_color = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int bt_button_disabled_color = 2131034138;
			
			// aapt resource value: 0x7f050023
			public const int bt_light_gray = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int bt_paypal_button_background = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int bt_paypal_button_background_pressed = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int bt_red = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int bt_very_light_gray = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int bt_white = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int bt_white_pressed = 2131034144;
			
			// aapt resource value: 0x7f050016
			public const int common_action_bar_splitter = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int common_signin_btn_dark_text_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_btn_dark_text_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_btn_dark_text_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_btn_dark_text_pressed = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int common_signin_btn_default_background = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int common_signin_btn_light_text_default = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_btn_light_text_disabled = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int common_signin_btn_light_text_focused = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_btn_light_text_pressed = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int common_signin_btn_text_dark = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int common_signin_btn_text_light = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int wallet_bright_foreground_disabled_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int wallet_bright_foreground_holo_dark = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int wallet_bright_foreground_holo_light = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int wallet_dim_foreground_disabled_holo_dark = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int wallet_dim_foreground_holo_dark = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int wallet_dim_foreground_inverse_disabled_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int wallet_dim_foreground_inverse_holo_dark = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int wallet_highlighted_text_holo_dark = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int wallet_highlighted_text_holo_light = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int wallet_hint_foreground_holo_dark = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int wallet_hint_foreground_holo_light = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int wallet_holo_blue_light = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int wallet_link_text_light = 2131034124;
			
			// aapt resource value: 0x7f050026
			public const int wallet_primary_text_holo_light = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int wallet_secondary_text_holo_dark = 2131034151;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int bt_default_item_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int bt_default_small_text_size = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int bt_default_text_size = 2131296258;
			
			// aapt resource value: 0x7f09000d
			public const int bt_floating_edit_text_horizontal_offset = 2131296269;
			
			// aapt resource value: 0x7f090003
			public const int bt_form_appswitch_button_size = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int bt_form_field_padding = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int bt_form_padding = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int bt_full_width = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int bt_header_container_height = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int bt_input_text_size = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int bt_landscape_max_width = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int bt_payment_method_button_divider_height = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int bt_payment_method_button_divider_width = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int bt_payment_method_button_height = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int bt_payment_method_button_type_padding = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int bt_payment_method_item_padding = 2131296268;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bt_amex = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bt_android_pay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bt_card_highlighted = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bt_cid_highlighted = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bt_cvv_highlighted = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bt_diners = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bt_discover = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bt_error = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bt_jcb = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bt_loading = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bt_loading_animation = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bt_logo_android_pay = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bt_logo_paypal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bt_logo_venmo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bt_maestro = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bt_mastercard = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bt_payment_button_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bt_paypal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bt_secure = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bt_submit_button_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bt_success = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bt_venmo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bt_visa = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bt_white_with_border_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_full_open_on_phone = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_ic_googleplayservices = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_disabled_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_disabled_focus_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_icon_disabled_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_focus_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_icon_focus_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_icon_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_icon_normal_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_icon_normal_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_icon_pressed_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_icon_pressed_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_disabled_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_disabled_focus_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_disabled_focus_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_text_disabled_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_focus_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_signin_btn_text_focus_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_signin_btn_text_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_signin_btn_text_normal_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_signin_btn_text_normal_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_signin_btn_text_pressed_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_signin_btn_text_pressed_light = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001d
			public const int adjust_height = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int adjust_width = 2131361822;
			
			// aapt resource value: 0x7f0a000a
			public const int book_now = 2131361802;
			
			// aapt resource value: 0x7f0a0034
			public const int bt_android_pay_button = 2131361844;
			
			// aapt resource value: 0x7f0a0042
			public const int bt_card_form = 2131361858;
			
			// aapt resource value: 0x7f0a001f
			public const int bt_card_form_card_number = 2131361823;
			
			// aapt resource value: 0x7f0a0021
			public const int bt_card_form_cvv = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int bt_card_form_expiration = 2131361824;
			
			// aapt resource value: 0x7f0a0040
			public const int bt_card_form_header = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int bt_card_form_header_bar = 2131361857;
			
			// aapt resource value: 0x7f0a0022
			public const int bt_card_form_postal_code = 2131361826;
			
			// aapt resource value: 0x7f0a0029
			public const int bt_card_form_submit_button = 2131361833;
			
			// aapt resource value: 0x7f0a002b
			public const int bt_change_payment_method_link = 2131361835;
			
			// aapt resource value: 0x7f0a0038
			public const int bt_description_amount = 2131361848;
			
			// aapt resource value: 0x7f0a0035
			public const int bt_description_container = 2131361845;
			
			// aapt resource value: 0x7f0a003e
			public const int bt_form_scroll_container = 2131361854;
			
			// aapt resource value: 0x7f0a003d
			public const int bt_header_container = 2131361853;
			
			// aapt resource value: 0x7f0a002c
			public const int bt_header_loading_spinner = 2131361836;
			
			// aapt resource value: 0x7f0a002e
			public const int bt_header_message = 2131361838;
			
			// aapt resource value: 0x7f0a002d
			public const int bt_header_status_icon = 2131361837;
			
			// aapt resource value: 0x7f0a0024
			public const int bt_inflated_loading_view = 2131361828;
			
			// aapt resource value: 0x7f0a0028
			public const int bt_inflated_payment_method_form = 2131361832;
			
			// aapt resource value: 0x7f0a0026
			public const int bt_inflated_payment_methods_list = 2131361830;
			
			// aapt resource value: 0x7f0a0044
			public const int bt_loading_progress_bar = 2131361860;
			
			// aapt resource value: 0x7f0a003f
			public const int bt_payment_button = 2131361855;
			
			// aapt resource value: 0x7f0a0031
			public const int bt_payment_button_divider = 2131361841;
			
			// aapt resource value: 0x7f0a0033
			public const int bt_payment_button_divider_2 = 2131361843;
			
			// aapt resource value: 0x7f0a003b
			public const int bt_payment_method_description = 2131361851;
			
			// aapt resource value: 0x7f0a0039
			public const int bt_payment_method_icon = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int bt_payment_method_type = 2131361850;
			
			// aapt resource value: 0x7f0a002f
			public const int bt_payment_method_view_switcher = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int bt_paypal_button = 2131361840;
			
			// aapt resource value: 0x7f0a0036
			public const int bt_primary_description = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int bt_secondary_description = 2131361847;
			
			// aapt resource value: 0x7f0a002a
			public const int bt_select_payment_method_submit_button = 2131361834;
			
			// aapt resource value: 0x7f0a0043
			public const int bt_selected_payment_method_view = 2131361859;
			
			// aapt resource value: 0x7f0a0023
			public const int bt_stub_loading_view = 2131361827;
			
			// aapt resource value: 0x7f0a0027
			public const int bt_stub_payment_method_form = 2131361831;
			
			// aapt resource value: 0x7f0a0025
			public const int bt_stub_payment_methods_list = 2131361829;
			
			// aapt resource value: 0x7f0a0032
			public const int bt_venmo_button = 2131361842;
			
			// aapt resource value: 0x7f0a0006
			public const int buyButton = 2131361798;
			
			// aapt resource value: 0x7f0a000b
			public const int buy_now = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int buy_with = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int buy_with_google = 2131361805;
			
			// aapt resource value: 0x7f0a003c
			public const int card_form_root = 2131361852;
			
			// aapt resource value: 0x7f0a0011
			public const int classic = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int donate_with = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int donate_with_google = 2131361807;
			
			// aapt resource value: 0x7f0a0012
			public const int google_wallet_classic = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int google_wallet_grayscale = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int google_wallet_monochrome = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int grayscale = 2131361813;
			
			// aapt resource value: 0x7f0a0000
			public const int holo_dark = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int holo_light = 2131361793;
			
			// aapt resource value: 0x7f0a0019
			public const int hybrid = 2131361817;
			
			// aapt resource value: 0x7f0a0010
			public const int logo_only = 2131361808;
			
			// aapt resource value: 0x7f0a0008
			public const int match_parent = 2131361800;
			
			// aapt resource value: 0x7f0a0016
			public const int monochrome = 2131361814;
			
			// aapt resource value: 0x7f0a0045
			public const int myButton = 2131361861;
			
			// aapt resource value: 0x7f0a0017
			public const int none = 2131361815;
			
			// aapt resource value: 0x7f0a001a
			public const int normal = 2131361818;
			
			// aapt resource value: 0x7f0a0002
			public const int production = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int sandbox = 2131361795;
			
			// aapt resource value: 0x7f0a001b
			public const int satellite = 2131361819;
			
			// aapt resource value: 0x7f0a0007
			public const int selectionDetails = 2131361799;
			
			// aapt resource value: 0x7f0a0018
			public const int slide = 2131361816;
			
			// aapt resource value: 0x7f0a0004
			public const int strict_sandbox = 2131361796;
			
			// aapt resource value: 0x7f0a001c
			public const int terrain = 2131361820;
			
			// aapt resource value: 0x7f0a0005
			public const int test = 2131361797;
			
			// aapt resource value: 0x7f0a0009
			public const int wrap_content = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int bt_match_parent = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int bt_card_form_fields = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bt_drop_in_ui = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int bt_form_submit_button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int bt_list_submit_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int bt_loading_header = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int bt_loading_view = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int bt_payment_button = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int bt_payment_description = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int bt_payment_method = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int bt_payment_method_form = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int bt_payment_methods_list = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int bt_secure_loading_progress_bar = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Main = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060040
			public const int app_name = 2131099712;
			
			// aapt resource value: 0x7f060004
			public const int auth_google_play_services_client_facebook_display_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int auth_google_play_services_client_google_display_name = 2131099651;
			
			// aapt resource value: 0x7f060023
			public const int bt_add_new_payment_method = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int bt_add_payment_method = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int bt_card_descriptor = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int bt_change_payment_method = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int bt_choose_payment_method = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int bt_default_action_bar_text = 2131099688;
			
			// aapt resource value: 0x7f06003a
			public const int bt_default_action_label = 2131099706;
			
			// aapt resource value: 0x7f060029
			public const int bt_default_submit_button_text = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int bt_descriptor_amex = 2131099690;
			
			// aapt resource value: 0x7f060037
			public const int bt_descriptor_android_pay = 2131099703;
			
			// aapt resource value: 0x7f06002b
			public const int bt_descriptor_diners = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int bt_descriptor_discover = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int bt_descriptor_jcb = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int bt_descriptor_maestro = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int bt_descriptor_mastercard = 2131099695;
			
			// aapt resource value: 0x7f060038
			public const int bt_descriptor_pay_with_venmo = 2131099704;
			
			// aapt resource value: 0x7f060030
			public const int bt_descriptor_paypal = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int bt_descriptor_unknown = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int bt_descriptor_visa = 2131099698;
			
			// aapt resource value: 0x7f06003b
			public const int bt_form_hint_card_number = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int bt_form_hint_cvv = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int bt_form_hint_expiration = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int bt_form_hint_postal_code = 2131099710;
			
			// aapt resource value: 0x7f060033
			public const int bt_form_pay_with_card_header = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int bt_invalid_card = 2131099700;
			
			// aapt resource value: 0x7f060039
			public const int bt_pay_with_android_pay = 2131099705;
			
			// aapt resource value: 0x7f060035
			public const int bt_pay_with_paypal = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int bt_pay_with_venmo = 2131099702;
			
			// aapt resource value: 0x7f060007
			public const int common_android_wear_notification_needs_update_text = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int common_android_wear_update_text = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int common_android_wear_update_title = 2131099666;
			
			// aapt resource value: 0x7f060020
			public const int common_google_play_services_api_unavailable_text = 2131099680;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_enable_button = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_enable_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_enable_title = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_error_notification_requested_by_msg = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_install_button = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_install_text_phone = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_install_text_tablet = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_install_title = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_invalid_account_text = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_invalid_account_title = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_needs_enabling_title = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_network_error_text = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_network_error_title = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_needs_update_title = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_notification_ticker = 2131099653;
			
			// aapt resource value: 0x7f060022
			public const int common_google_play_services_sign_in_failed_text = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int common_google_play_services_sign_in_failed_title = 2131099681;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_unknown_issue = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_unsupported_text = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_unsupported_title = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_update_button = 2131099678;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_text = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_update_title = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_updating_text = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_updating_title = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int common_open_on_phone = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_button_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_button_text_long = 2131099650;
			
			// aapt resource value: 0x7f06003f
			public const int hello = 2131099711;
			
			// aapt resource value: 0x7f060000
			public const int wallet_buy_button_place_holder = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int WalletFragmentDefaultButtonTextAppearance = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int WalletFragmentDefaultDetailsHeaderTextAppearance = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int WalletFragmentDefaultDetailsTextAppearance = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int WalletFragmentDefaultStyle = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int bt_app_switch_button_divider = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int bt_base_textview = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int bt_base_textview_bold = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int bt_card_form_field = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int bt_card_form_field_landscape = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int bt_form_appswitch_button = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int bt_horizontal_gray_line = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int bt_main_view_controller_container = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int bt_payment_method_app_switch_button = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int bt_submit_button = 2131165194;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomWalletTheme = new int[]
			{
					2130771983};
			
			// aapt resource value: 0
			public const int CustomWalletTheme_windowTransitionStyle = 0;
			
			public static int[] LoadingImageView = new int[]
			{
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] PaymentButtonAttributes = new int[]
			{
					2130772004};
			
			// aapt resource value: 0
			public const int PaymentButtonAttributes_tokenizationKey = 0;
			
			public static int[] WalletFragmentOptions = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int WalletFragmentOptions_appTheme = 0;
			
			// aapt resource value: 1
			public const int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public const int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public const int WalletFragmentOptions_fragmentStyle = 2;
			
			public static int[] WalletFragmentStyle = new int[]
			{
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 3
			public const int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public const int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public const int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public const int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public const int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public const int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public const int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public const int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public const int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public const int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public const int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
